name: Lint, Build, Deploy

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "2.4.5"
      - name: Run Biome
        run: biome ci .

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: vegardege/bookbear:latest
          platforms: linux/amd64

      - name: Build and push pipeline image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.pipeline
          push: true
          tags: vegardege/bookbear-pipeline:latest
          platforms: linux/amd64
